name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: 0.19.1
        use-tool-cache: true

    - name: Build
      run: cargo build

    - name: Run tests with coverage
      working-directory: ./entab
      run: cargo +nightly tarpaulin --all --timeout 600 --out Xml -- --test-threads 1

    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  misc_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run no_std tests
      working-directory: ./entab
      run: cargo test --no-default-features
